### ISSUE TITLE
Request: Make 'BreadCrumBar' a standalone option in Preferences

### ISSUE THREAD

**Issue by CodeMarc11** [FrankBijnen/ExifToolGui#204]
Request: Could showing 'BreadCrumBar' be broken out to its own option in Preferences? It could go right below Show Folders. Also, could it be called something more familiar, maybe "Show Address Bar", to borrow the UI term "Address Bar" from File Explorer? Even as a tech person, I was not familiar with BreadCrumBar, so people might not know that.

![Address Bar request](https://github.com/FrankBijnen/ExifToolGui/assets/38742926/846149b2-6872-4306-8b14-e0be99365d1b)

Ref: Add BreadCrumb Bar https://github.com/FrankBijnen/ExifToolGui/issues/195

**Comment by FrankBijnen** [comment]
A good idea. I had thought about it, but hesitated because I dont want too many parameters in preferences.

The term BreadcrumbBar comes from Andreas Rejbrand, he gave me permission to use the sourcecode.
'Scaling of the breadcrumb'. Does is look like the rest of the UI on a different monitor? Is it readable? etc?

**Comment by FrankBijnen** [comment]
Will be in V6.2.7

![preferences_other](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e754cf2b-3c7b-446c-91f1-faef050ee230)
