### ISSUE TITLE
Can not navigate beyond hidden folders on windows.

### ISSUE THREAD

**Issue by ErikKrause** [FrankBijnen/ExifToolGui#236]
I'm so grateful to have this tool again, many thanks! However, it shares a flaw with the old version: It can not navigate into hidden folders, like f.e. AppData, even if I have windows explorer configured to show hidden files and folders. This is especially annoying, when I pass a filename to  ExifToolGUI from the command line.

**Comment by FrankBijnen** [comment]
You're Welcome.

_However, it shares a flaw with the old version._

I dont agree that the old version did show hidden and or system folders/files. 

- The old version used TJamShellTree/View. I had a look in the old source code and online docs. The Property <b>ShowHidden</b> should have been set. It is nowhere to be found in the source! 
- See: https://manuals.jam-software.com/shellbrowser_delphi/EN/ShellControls_TJamShellTree_ShowHidden.html

- I created a test folder, with a combination of Hidden/System and normal folders/files. See the attached Zip.  Have a look at how V628, V516 and windows Explorer display it. V516 and V628 are the same!

Zip file. Please check for yourself with the old version you have: [Attributes.zip](https://github.com/FrankBijnen/ExifToolGui/files/13818227/Attributes.zip)

Compare window:
![Compare](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/ee0400d5-2915-4da1-a590-bfb605a355a1)

- I did check older versions and compared it with Windows explorer. NO hidden or system folders neither.

Version: V3.42
![V3 42](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/a904e416-8aa0-4b2c-8aba-a883b3b674e9)

Version: V4.27
![V4 27 1 0](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/8eda019e-5715-492a-9945-3135b8d78b35)

Version: V5.16
![V5 16 0 0](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/8403b225-6208-46af-888d-d604c7815dcd)

Having said that, It could be an idea to have an option to enable that. So I enabled it in code and tried it. I was soon convinced this was not something to enable.

- Users could potentially harm their system.
- A lot of work would be needed to prevent error messages. See what happens if you browse to 'PageFile.sys' or 'Documents & Settings'
- There are no benefits for most users.

![Documents and settings](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/187d0a8a-d7ee-4bf0-b8e3-2b9aae45ea48)
![PageFile](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/96ad6930-df8a-47f8-ba50-9379167518b2)

**Comment by ErikKrause** [comment]
No, the old version didn't show hidden files and folders, and I found that annoying. Any windows user can decide to show hidden files and folders, and I don't think it's a good idea to be more protective than microsoft. In the end, it is an incapacitation of the user. And consider, that users, who are interested in more metadata than explorer shows are generally more computer-savvy than usual.

**Comment by FrankBijnen** [comment]
Reading your initial post again. "It <b>shares</b> a flaw". Now I agree completely!

Will think about a 'safe solution'. Promised. It will have to be something that the user deliberately asks for.

**Comment by ErikKrause** [comment]
Many thanks! I don't know whether it's possible to query the windows setting, but an option with a warning would certainly do that.

**Comment by FrankBijnen** [comment]
Hello Erik,

I have been thinking, and I come up with this possible solution.

1) Add a checkbox in preferences 'Show hidden folders/files in filelist' 
2) If the checkbox is checked AND ExifToolGui was started as admin, then hidden folders will be shown.

This way you have to choose explicitly and you must be an admin. 

My questions to you:
- Would that suit your needs?
- Would you like to test it when I have something, or will you wait for a next release?

Frank

**Comment by ErikKrause** [comment]
Does the requirement to be an administrator mean that I have to confirm a dialog every time I start ETG, or do I simply have to be a user with administrator rights, in which case ETG would just start? The second case would be very welcome, the first not so much. But I'd be grateful if it worked at all, especially from the command line, since I use ETG from the SendTo menu.
And yes, I'd like to test any beta releases.

**Comment by FrankBijnen** [comment]
The Beta that I could send you tomorrow will popup every time you start. You can change that setting in 'User Account Control', but that change would be 'System Wide', not just for ETG. 
If you first start an elevated CMD prompt, and from that prompt you start ETG it will not prompt you.
Please have a look first, we can discuss this later.

I could send the Exe + map file via Wetransfer, but then I would need an email address. Or do you prefer an other option?

Frank

**Comment by ErikKrause** [comment]
Am 05.01.2024 um 00:15 schrieb FrankBijnen:

> I could send the Exe + map file via Wetransfer, but then I would need
> an email address.

That would be fine

--
Erik Krause

**Comment by FrankBijnen** [comment]
@ErikKrause Thanks for testing

**Comment by FrankBijnen** [comment]
Just to let you know, This change is now available in a new release.

https://github.com/FrankBijnen/ExifToolGui/releases/tag/V6.2.9

Thanks again,
Frank
