### ISSUE TITLE
Feature Request: Changing the model name to XYZ if the model name is ABC for a whole folder

### ISSUE THREAD

**Issue by hubertmeier** [FrankBijnen/ExifToolGui#244]
This is a feature request for a special case ... There is RAW development software which exclude new camera modells. If the Sony ILCE-7CR is not known, i can change manually the modell name to ILCE-7RM4 (same sensor), i can work without problems and after that, i change in the result the model back to ILCE-7CR. I have another ILCE-7C (without R), change the model to ILCE-7M3 /same sensor) and it works.

I am looking for a batch conversion, i tried with windows batch and exiftool, i tried with python and syscalls and had no success. Linux bash could be easier but i have to do it in windows...

I want to have both models in the same folder, so there has to be testing for the model like this for the whole folder

**IF** model=ILCE-7C **THEN CHANGE** model=ILCE-7M3
IF model=ILCE-7CR THEN CHANGE model=ILCE-7RM4

and after editing ...

IF model=ILCE-7M3 THEN CHANGE model=ILCE-7C
IF model=ILCE-7RM4 THEN CHANGE model=ILCE-7CR

when there are other models then there is nothing to change.

would this be possible?

Thank you for your work

**Comment by FrankBijnen** [comment]
Hello Hubert,

Thanks for your question! I like these questions, because they give me a good insight how people are using Exiftool(GUI)

First of all, if this could be handled by ExifTool it would be the preferred solution. Believe it or not I have never used IF statements in ExifTool. I'm a Delphi programmer! I think it would be a good idea to search in this forum https://exiftool.org/forum/ , and maybe ask your question there. StarGeek and Phil Harvey check regularly for questions.
If it turns out that ExifToolGui needs changing to use the proposed ExifTool solution, let me know!

If it has to be done In ExifToolGui without changes, this is how I would do it.

1) Add 'Model' to the 'user defined' filelist.
![add2filelist](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/9f70c1ac-924e-417c-8514-e327bd95d2eb)

2) Create one or more predefined commands to change the model. (Maybe you can use an IF statement, I would have to try it)
The Double quotes are needed if you have spaces in your data.
![makeepre](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/c5e0546c-3fc7-47dd-bca6-b46452922a86)

3) Browse to the folder, and sort on the column model that you just created.
4) Select the files with the model you want to change. (Use Shift/Ctrl cursor up/down)
5) Execute the predefined command to change the model.

![doit](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/6935de17-677e-49d6-a953-591f065d7e02)

Frank

**Comment by FrankBijnen** [comment]
I did a quick test with an If statement. These 2 statements work:

-ifd0:model="PENTAX K-x" -if "$model eq 'PENTAX K-5 II s'"

-ifd0:model="PENTAX K-5 II s" -if "$model eq 'PENTAX K-x'"

Please pay attention to the single and double quotes!

This is how it looks in GUI:
![tok5](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/e6a9b39b-844c-4271-aa47-b14375b3fd2c)

P.S.: When you open the log window, you can create a powershell script, that you can maybe use as a starting point for your own script.
![logwindow](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/af389baf-359d-4548-915a-35fbc68668b7)

**Comment by hubertmeier** [comment]
Wow ... what a support! Yes, this seems to be a good way, i succesfully changed the model name with conditions.

**Changemodell ILCE-7C -> ILCE-7M3**
-ifd0:model="ILCE-7M3" -if "$model eq 'ILCE-7C'"

**Changemodell ILCE-7M3 -> ILCE-7C**
-ifd0:model="ILCE-7C" -if "$model eq 'ILCE-7M3'"

**Changemodell ILCE-7CR -> ILCE-7RM4**
-ifd0:model="ILCE-7RM4" -if "$model eq 'ILCE-7CR'"

**Changemodell ILCE-7RM4 -> ILCE-7CR**
-ifd0:model="ILCE-7CR" -if "$model eq 'ILCE-7RM4'"

A simple button "Select all" would be nice, so i use CTRL-a to mark all files, then i select my predefined command. Can you tell me, where the user-defined commands are stored? The two .ini files do not seem contain the commands, the last file seems to be binary.

Thank you so much for your help. I think, these hints are very useful for other people.

**Comment by FrankBijnen** [comment]
Thanks for testing and reporting back.

The commands are stored in the INI file in %APPDATA%\ExiftoolGui\ExifToolGuiV6.ini.
Look for the section: [ETdirectCmd]

I will close this Issue.

Frank
