### ISSUE TITLE
Video files show composite GPS coordinates but cannot update City, Country, etc

### ISSUE THREAD

**Issue by renschmid** [FrankBijnen/ExifToolGui#258]
My mp4 video files have Composite GPS Coordinates like: 42.945000° N, 76.432700° W. They also appear as separate Longitude and Latitude fields.

Using the Update function under the Modify Tab report that the coordinates are not valid.

**Comment by FrankBijnen** [comment]
Hello,

This issue is related: https://github.com/FrankBijnen/ExifToolGui/issues/251

First let me explain what is the cause.
- The batch update 'City, Country etc' that I created should be as fast as possible. It could involve a lot of files!
- Obviously for every file the GPS coordinates are needed. Bogdan Hrastnik, the original developer, had made code to read the GPS coordinates very fast by reading the files directly, I have used that code, but it does not work for all file types.

Long term solution:
- I recently added support for CR3 files, as you can see in issue 251. But to add Video files, or other file type would be too much.
- I will change the code: If the file type is supported use the fast code, if not fallback to calling ExifTool.
- It will slow-down the process for those file type.

Workaround for the short term:
- Select one or more files with the same location.
- Click on 'Show on Map' in the 'OSM Map' tab.
- Click on 'Geotag files' at the bottom.
- Verify that the data displayed in the Dialog is correct.
- Optionally you can type something into the 'Location' field.
- Make sure 'Update in selected files:' is set to 'Location (Country, Province, City)' So the GPS Coordinates are not overwritten

![geotag](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/1031eef0-7a6b-4e74-bd7c-fc9c4e74825f)

The data will not be shown in the Filelist when you set that to 'Location info' but you can add the fields to 'User Defined'. (The user-defined view is also slower than the location-info view, because it does not use the fast code)

![userdef](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/52895f9d-ae55-42ac-a5a9-4d680cdc9ddf)

**Comment by FrankBijnen** [comment]
I have done some investigating, and already made some changes. But I need some info.
I would like to know in what group the GPS info is stored in your MP4 files. Can you run this command and post the output here?

exiftool -g -a -gpslatitude -gpslongitude <yourfile.mp4>

it show something like:
---- XMP ----
GPS Latitude                    : nn.ddddddd° N
GPS Longitude                  : nn.ddddd° E
{ready34}

My mp4 files store their coordinates in the XMP group, but ExifToolGui only updates the GPS: <EXIF> group.

Thanks
Frank

**Comment by FrankBijnen** [comment]
I have been digging deeper, and even asked Phil Harvey for advice. As it stands now even the 'Workaround for the short term:' will not work.

Will look into it

**Comment by renschmid** [comment]
I apologise for taking so long to respond. We live near Sydney, Australia and received your email during the night.

Here is the information you requested:

C:\Users\renal\Downloads\exiftool-12.73>exiftool -g -a -gpslatitude -gpslongitude 20230923_125319.mp4
---- Composite ----
GPS Latitude                    : 43 deg 5' 18.60" N
GPS Longitude                   : 79 deg 4' 27.84" W

I have many video files from a Samsung S23 Ultra that I want to rename with capture date, location and time. For example (using the file above), 2023-09-23_City State Country_125319. The last number is the time, and it allows me to keep my video shots in the order that I shot them. I have an excellent file manager called Directory Opus, that can bulk rename files using metadata fields. I can access any metadata field through an add-in that uses the exiftool to map the fields to use during batch rename.

Yesterday, I:

- Copied the Composite GPS Coordinates from a video file using Extool GUI; 
- Pasted it into the OSM Find field 
- Edited the result to look like: 42.9451, -76.4232.
- The map resolved to the correct location.
- I then clicked "Get Geo Tags"

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/d0c9d42d-55c9-4bec-b3b9-57e6b7cb4be3)

**_Note: I did not make an entry for "Location". What is that used for?_**

**Exiftook correctly updated the video file metadata.**

While this method was successful, it was very slow because I had to change the geolocation coordinates manually for each video file to ensure accurate data. Is there a quicker way to translate GPS Latitude 43 deg 5' 18.60" N
GPS Longitude  79 deg 4' 27.84" W to 42.9451, -76.4232?

_I note that the composite field in ExiftoolGUI is 42.945100° N, 76.423200° W_

![image](https://github.com/FrankBijnen/ExifToolGui/assets/47437/295e01f1-37fb-415e-a2b0-4a373ee995b7)

This image shows the updated fields.

A good solution involves translating the composite field into the decimal format that OSM Map and the underlying reverse lookup servers can use. This should result in a bulk update solution, albeit limited to the 1-second restriction. Most domestic users can live with that and accept 500 seconds to update 500 files. It is much better than doing it manually!

I am not a programmer, but can appreciate that coding techniques can result in faster processing.

Thank you for taking the time to develop extoolGUI and for your thorough approach to engaging with users. I really appreciate your responses.

Rennie

**Comment by FrankBijnen** [comment]
"Note: I did not make an entry for "Location". What is that used for?"
It's a 'free field'. For your reference. Examples: 'Pete's bar'. 'Good restaurant', 'Summit' etc. anything you like.
For supported files types it will show in the filelist if you set it to 'Location info'
![location](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/79693693-6b89-471a-bc1f-9eddb2b6cf82)

About the Coordinates notation: ExifToolGui should handle that, when all functions work as expected. In the Edit field in the OSM map you should always use the Decimal notation

The problem that I will try to solve today (Local time now is 11.00 AM approx) to set the fields as adviced by Phil Harvey. The problem is that for MP4 files the data should be stored in a different group compared to images (JPG etc) That's what I needed you to confirm with the ExifTool Command.
By the end of the day I should have a 'Prerelease' ready, that you can test if you like. Would you like to do that?

Keep you posted,
Frank

**Comment by renschmid** [comment]
Yes, Frank, I can test it, but I may not get to it until after 4 pm tomorrow. It is now nearly 9.30 pm in Sydney.

**Comment by FrankBijnen** [comment]
Take your time. (No worries)

**Comment by FrankBijnen** [comment]
Hi Rennie.

Here is the downloadlink for the pre-release. It's only the X64 executable + map (no 32 bits)

https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

Please use some test files first. Or files that you have backed up.  Start with a few. Remember this is a pre-release

If your files already contain GPS coordinates and you want to add Country,Province, City:
- (Multi) select the files you want to update in the filelist. 
- Choose Modify/Update Country .... from GPS Coordinates.
- OK

If your file dont contain GPS Coordinates.
- (Multi) select the files you want to update in the filelist. Take care to select file of the same type! (So dont make a selection containing JPG and MP4 files.)
- Choose the location on the OSM map. You can use the search, or paste decimal Lat, Lon values, or just pan the map. Tip: Use Ctrl+ left click to precisely choose the location.
- Click on Geotag files
- The values displayed can be altered.
- Choose to update: Coordinates, Location, or Both
-Execute

Take your time. I really appreciate your feedback!
Frank

**Comment by renschmid** [comment]
Hi Frank,

I copied a video folder and modified the files using your method. It worked. Congratulations.

This is the error I received using these settings:

***@***.***


[A screenshot of a computer error message  Description automatically generated]

Pressing “YES” enabled to process to continue.


I also tried using  It worked the best but occasionally threw this error:

***@***.***


Adding Geo Coordinates to files was a different story. I will send you a second response with the details.

I have a 1 sec limited API key.


Regards

Rennie

**Comment by renschmid** [comment]
I have  large video that won’t accept the coordinates location data. This is the dialogue and following you will see the error.

***@***.***


[A screenshot of a computer  Description automatically generated]
Regards

Rennie

**Comment by FrankBijnen** [comment]
Hi Rennie,

Thanks for testing. Too bad the success is only partial!

The error messages in both your mails dont show. This is how it looks.
![mail](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/966aa9f5-3b6d-4f6c-91de-9a3444d62120)

To get the error messages this is what you can do. Click on 'Show Log window' (Center Bottom) Keep this window open.
No repeat the actions that give you the error message(s). They should be visible in the Log Window afterwards. You can Select (Ctrl+A) and copy (Ctrl+C) the text from the log window and paste them here in the issue.

If understand correctly there are 2 problems,
- A large file that wont update. I really would like to see the error message for that one.
- Sometimes an error, possibly related to the GeoCode provider. You can try 2 things.
1) Increase the 'Throttle value' in preferences. 
2) Change to OverPass. For looking up Country, Province and City this is my preferred choice.
And yes I still would like to see the error message

Frank

**Comment by renschmid** [comment]
Sorry, they displayed my end. I will try again tomorrow and put them up via the Web page rather than using Outlook.

I have used both Overpass and Geocode. Geocode worked with fewer errors.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
