### ISSUE TITLE
[FEATURE] How can I add a translation?

### ISSUE THREAD

**Issue by GabrielOsvair** [FrankBijnen/ExifToolGui#271]
I would also love a dark mode. Congratulations on the project!

**Comment by FrankBijnen** [comment]
The short answer is: You cant add translations.
But its something on my wishlist. First I would have to enable translations in the program. I'm looking at alternatives.
Besides the program there is also a lot of documentation that would need to be translated. A huge amount of work.
I guess you are interested in Portuguese? 
Suppose I have something would you be willing to help?

About the dark mode: Go to Program/Style. If you choose 'Amakrits' or 'Auric' its pretty dark to me.

Frank

**Comment by FrankBijnen** [comment]
@GabrielOsvair 

Hello Gabriel. Meantime I know how translations can be done. If you're still interested contact me.

The actual translation will have to wait until Version 6.2.9 is released. I expect to do that end of Januari.

Frank

**Comment by GabrielOsvair** [comment]
I don't know much about programming, but I would like to help with the translation into Brazilian Portuguese, if you wish! So if I am helpful, how can I contact you?

**Comment by FrankBijnen** [comment]
Hello Gabriel,
A few quick replies:

"I don't know much about programming" That's OK. You dont have to.

"but I would like to help with the translation into Brazilian Portuguese,"  When it comes to Portuguese I cant help you, I speak a little Spanish.

"if you wish!" Well. To be clear about it. I would like to help people that are willing to translate to any language. All help is welcome, But Portuguese is not my priority. The languages I would like to do are Dutch, German, Spanish and French. 

"how can I contact you?" I dont want to publish my emailaddress here, But we can communicate via Github.

This is my plan:
- First release V6.2.9. End of this month.
- Then I can send you instructions on how to translate.
- You will be able to see the result of the translation directly in the program.
- Hopefully you send me the result, and I can add that to a future release.

Frank

This is a screenshot of the program you will be using.

![BTM](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/fed2e46c-7233-47e3-9e37-da9e604dbcd2)

**Comment by GabrielOsvair** [comment]
Alright, I'll check it out when it comes out.

**Comment by FrankBijnen** [comment]
Perfect.
Forgot to mention, I will do Dutch myself first, so I know what to expect. And hopefully I can explain other people better what to do.

Frank

**Comment by FrankBijnen** [comment]
Hello Gabriel,,

The new release is ready, and I did the preparations for translating. You can find the docs and needed files here:

https://github.com/FrankBijnen/ExifToolGui/tree/main/Translation

Dont hesitate to contact me if you have questions.

I did the translation to Dutch, my native language, myself and it took 12-15 hours. So be warned, it's quite some work.

**Comment by FrankBijnen** [comment]
@GabrielOsvair 

Hello Gabriel,

Any news? Have you started translating? 

Dont hesitate to contact me.

Frank

**Comment by GabrielOsvair** [comment]
Hello! Apologies for the delay. First weeks at the new job and it was crazy. I'll get started and let you know the progress.

**Comment by FrankBijnen** [comment]
Ah. Very well.

Please have a look at the docs: https://github.com/FrankBijnen/ExifToolGui/tree/main/Translation

I you have something ready, please upload ExifToolGUI_pt.xlat to this issue, and I will have a look.

Good luck

**Comment by GabrielOsvair** [comment]
Work started. Is there any way to translate automatically and I can just correct it? I imagine it will save a lot of time (DeepL currently doesn't support free API in my region and I don't know how to get the one from Microsoft).

![image](https://github.com/FrankBijnen/ExifToolGui/assets/67530921/0daf96f1-af64-46e3-bb30-b1c8e8fc8f8c)

**Comment by FrankBijnen** [comment]
@GabrielOsvair 

Hello Gabriel, 

1) About Deepl. I looked into it, but when they wanted my credit card I stopped. Dont want to give my credit card for a free account. They said they would not charge me, but i'm not sure.
2) About the Microsoft Azure API. I looked into it. But did not want to create an Azure account. If you find that it works good, let me know the details. I might just use it for other languages.

3) Meanwhile I have found another method.
- I created an Excel. See the attachment,
- You can paste the English text in the Deepl Wesbite. Start by 10 lines at a time.
- Copy from the Deepl site the Portuguese text into the Excel, under column PT

Please try it for a few lines. (10 - 50) and post the Excel file here. (Dont email me directly, because Github will discard the attachments)
I will try to import that into Better Translation Manager using 'Import from CSV'.

[ExifToolGUI_pt.xlsx](https://github.com/FrankBijnen/ExifToolGui/files/14277591/ExifToolGUI_pt.xlsx)


![Deepl website](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/d6489eac-eeca-4033-86b1-4f0e01b13dee)

**Comment by FrankBijnen** [comment]
@GabrielOsvair 

Hello Gabriel. 

I have closed this issue and opened a new one.  Please have a look at: https://github.com/FrankBijnen/ExifToolGui/pull/319

I did that for all languages that were translated, but need checking.

Frank
