### ISSUE TITLE
Feature Request: Display the imported gps file track on the map.

### ISSUE THREAD

**Issue by Philshappy** [FrankBijnen/ExifToolGui#340]
It would be nice to display the imported gps file track on the map. then one could see how the photos are synchronized to the gps file. if there are multiple files maybe have a check box or selection.

**Comment by FrankBijnen** [comment]
I think you mean the GPX files you can select when you use 'Export/Import' 'Import GPS data from'

Need to think about it. The problem is that that function is technically unrelated to the map.
Will keep the issue open. But it will be something for the long term.

**Comment by FrankBijnen** [comment]
@Philshappy 

I have (finally) completed this issue, That is, I think it is completed, but I would like to hear your opinion.  A few hints on how to use it:

1) From Export/Import, Import GPS data from, Log Files..
When you have chosen a log file, the button 'Show on map' is enabled.
![import](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/55d8eadf-aca7-4de7-966c-bb24ee86855d)

2) From the Filelist. Select one or more Log files, and click on 'Show on map'.
![filelist](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/73ae28e0-0c0d-45f6-bc48-f9b0d9953c67)

Note: You can combine it with 'Image files'

- In the Map a small blue button is added. Using that you can (de)select individual log files
![deselect](https://github.com/FrankBijnen/ExifToolGui/assets/63312605/a65d617a-7ba6-47ac-93d4-27d8ee6c044a)

- When you click on 'Home' the log files are removed from the map.

I have only tested with GPX files, because those are the only ones I have. But it should work with any log file supported by Exiftool

Frank

You can download a prerel here:
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

**Comment by Philshappy** [comment]
Wow! Great new capability. I have some comments after testing but in general it works great. 
1) It would be nice to have an option to display a smaller box/icon of an image info on the map. When multiple images are included it makes seeing the map difficult. See photo Smaller Box
2) When more than 1 GPX file is loaded they get connected. They should not be. See photo Connected GPX files. The highlighted GPX files are to seperate tracks that were connected.
3) If you selected the Export/Import>Import GPS aata from>Log files and you select/open a non GPX file such as a JPG the Show on Map button is highlighted although it does nothing when pressed.
4) The blue option box to select/deselect GPX files is a great feature and if you get free time it would be great to add the selected image files as well.
![Smaller Box](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/e8042a9a-812b-4389-bc13-71ba652a9619)
![Connected GPX Files](https://github.com/FrankBijnen/ExifToolGui/assets/149206994/e6be2480-a04d-470a-aa34-6631d8fe3986)

**Comment by FrankBijnen** [comment]
Thanks for testing, and your feedback.

Here are my comments:

1) I understand what you're saying. 
- It looks like you've setup your display to use scaling. That makes it even worse.
- I'm thinking of using a smaller font. Will try it on different screens.
- Actually you can control it yourself. Hold (left)Ctrl and turn the mouse wheel. The setting will not be saved!
2) Good point! I have corrected it.
3) I dont see the problem here. I could maybe add some checks and warn the user 'Your log file is incorrect!' But I imagine the average GUI user is smart enough to figure it out themselves.
4) Again a good point. But not something I can fix (easily). The image popups can not be assigned to a layer, and that is required for the blue button.

Frank
P.S. Will be available in a next version.

**Comment by Philshappy** [comment]
I may not have explained #3 correctly. When you Export/Import >Import Data> from log files and select a non log file such as a JPEG the Show Map button should not light up but should stay dark since the Log file that was selected is a non valid log file but a JPEG. This is minor, since pressing the button does nothing.

**Comment by FrankBijnen** [comment]
> I may not have explained #3 correctly. When you Export/Import >Import Data> from log files and select a non log file such as a JPEG the Show Map button should not light up but should stay dark since the Log file that was selected is a non valid log file but a JPEG. This is minor, since pressing the button does nothing.

Indeed I did not think that was what you meant.
The 'logic' to enable the button is the same as the 'Execute' button. They go dark, or bright, together.
To be sure that the log file entered is valid I would have to process the file(s). And that could be quite time consuming.

Glad you consider it minor.

**Comment by Philshappy** [comment]
Could you not just look at the file extension, if it not a GPX or other valid type, then do not consider it valid.

**Comment by Philshappy** [comment]
Could you not just look at the file extension, if it not a GPX or other valid type, then do not consider it valid.
