### ISSUE TITLE
Using Ctrl-A to select all files does not seem to work consistently for me

### ISSUE THREAD

**Issue by SneeziePacker** [FrankBijnen/ExifToolGui#394]
Hello, I first want to give you a HUGE thank you for the work you've done on this app. I'm a photo organizer (that's actually a "thing") and I use Exiftool in some way every single day. I used the older version of ExifToolGui and am thrilled with the updates you have made and are continuing to make!

I'm a heavy user of the keyboard and have noticed inconsistent behavior when I use Ctrl-A as a shortcut to select all files. Occasionally it works fine, it seems most often after I've selected one of the displayed files. Other times in the same scenario, it doesn't appear to do anything and so I instead click on the first and then ctrl-click on the last file, but it's adds time and keystrokes to do it that way. I also by habit click in a blank area of the Filelist area and press Ctrl-A but that doesn't seem to ever select all for me and I'm used to it doing so in other file management programs . I'd love it if I could rely on it to consistently select all of the files in the Filelist window.

I do notice that you do not have an Edit menu, so perhaps it is just luck that this works for me at all as that's where these shortcuts are typically listed. Thanks again.

**Comment by FrankBijnen** [comment]
Will look into it.
Give me some time

**Comment by FrankBijnen** [comment]
@SneeziePacker 

I just had a look at how the program handles shortcuts. Conclusions:

- There is indeed no Edit menu, but that doesn't affect the shortcuts.
- I dont agree that the behavior is inconsistent. I might not be want you expect, or what you want, but it works consistent.
- Ctrl-A works (consistent) when the filelist has the focus.
- Generally speaking the 'control that has the focus' processes the shortcut.
- If for example the Metadata panel has the focus, and you click on CTRL-C it copies the metadata value to the clipboard. If the FileList has the focus the selected file(name) is placed on the clipboard. 
- This general approach also applies to CTRL-A. But it may be confusing because CTRL-A does nothing for the Metadata Panel, it only does something for the FileList.

Putting it all together:
- It is programmed to work Generic for all shortcuts, the concept of 'control that has the focus' is important. And I want to keep that.
- I could however change the program to send CTRL-A always to the filelist. Even if the filelist does not have the focus. For the other shortcuts (CTRL-C, X, V etc.) this is not possible.

Let me know your thoughts.
Frank

**Comment by SneeziePacker** [comment]
Hi Frank,

After spending an hour trying to come up with a pattern of exactly when/why this happens in order to send details to you, I found the reason I felt there was inconsistency with Ctrl-A failing to work for me at times, is that I was typing the Ctrl and the A too quickly. If I slow it down and distinctly press Ctrl before A, then it does consistently select all files, each and every time. But if I type it fast, it gives the appearance of being inconsistent.

I was a programmer decades back and so Windows keyboard commands are so ingrained that I don't even think about them. While I have not ever ran into other programs where the speed on combo keys caused me an issue, I can certainly resolve this for myself in ExifToolGui by focusing on my speed using Ctrl-A. 

Any idea why the speed of key combos would behave differently in ExiftoolGui? Just curious at this point. 

One other question - is there a visual cue as to what panel has focus? 

Thanks much,

Kathy

**Comment by FrankBijnen** [comment]
@SneeziePacker 

Hi Kathy, Thanks for your detailed feedback. (And I mean that. Sometimes I get posts like 'Microsoft doesn't like your program. Nice try, but no')

First of all, I have made some changes and I created pre-rel V6.3.2. You can download it from here: https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

- I have looked into 'the timing' you reported. The program reacted on the 'KeyUp' message and checked for a pressed CTRL key. It could be that you release the CTRL Key, before you release the 'A' key. If have changed the event to 'KeyDown'. I think that will work better. Please test!
- With the pre-rel the program will also react on CTRL-A. even if the filelist doesn't have the focus.

About the visual cue:
- With issue https://github.com/FrankBijnen/ExifToolGui/issues/347 I have changed that the selected file is always clearly visible, even if the filelist does not have focus. It makes it easier to see on which file your working, but it makes it harder to see if the filelist has the focus.
- It can be observed though, but I agree not clearly. The background color will change slightly, depending on the style chosen.
- With this pre-rel I'm also drawing a focusrect. Appears as a dotted line around the selected file.

Usually you will switch focus between the MetaData panel, and the Filelist. If the Metadata panel doesn't have the focus (and that is obvious), it is likely the filelist that has the focus.  

Awaiting your reply,

Frank

**Comment by SneeziePacker** [comment]
That did the trick! Thank you!
