### ISSUE TITLE
Copying multiple files in the Filelist tab does not work (the old version allowed this)

### ISSUE THREAD

**Issue by butterflo** [FrankBijnen/ExifToolGui#43]
# Description

Copying multiple files in the Filelist tab does not work. The old version of ExifToolGUI (5.16.0.0) used to allow this.
This issue is observed in ExifToolGUI 6.1.0.0.

# Encouragements

This is a great project!! The old version was buggy but there wasn't a good alternative.

# Steps to reproduce

- In ExifToolGUI, navigate to a folder that contains image files.
- Select multiple files in the Filelist tab.
- Press keys Ctrl+C.
- In Windows, navigate to another folder.
- Press keys Ctrl+V.

# What I am expecting vs. what actually happens
- I am expecting the selected files to be copied to the destination folder.
- What actually happens, is the Ctrl+V does not do anything.

**Comment by FrankBijnen** [comment]
Hello butterflo,

I think this functionality was provided by the TJamShellList control,that I replaced by the standard Embarcadero TShellListView. 
Will look into the possibilty of doing something similar. 

One Question. You say 'In Windows, navigate to another folder.' Would it be acceptable if the Ctrl/V only works from within ExifToolGui? (That is also possible with the old version)

**Comment by butterflo** [comment]
Hi @FrankBijnen ,

Yes it looked like the underlying viewer was changed in some way.

To me, I am perfectly fine if the copy-pasting is doable only within ExifToolGUI.

Thank you!

**Comment by FrankBijnen** [comment]
Hello @butterflo ,

Lets start with the good news. I did an initial commit to the Development branch, With this update 2 things are accomplished.
1) You can use CTRL/C (When the ShellList has the focus) and paste in the Explorer. 
2) The Context menu, (What you get when you right-click in the ShellList) is now enabled for multi-select. Previously the commands only worked for 1 file. In this context-menu you can Copy/Cut and Delete multiple files.

What I have been looking for, but was unable to achieve until now, is a CTRL/X (Cut). That was possible in the old version, and also now from the context-menu. It turns out you have to implement some Interfaces to do this, and I think it gets to complex!
But since CTRL/X was not asked in the issue, I think you would be happy with the progress so far!

I dont want to do create a new release yet, people are still downloading 6.1.0 and may find more issues. But I would like you to test.
Can you build the executable yourself? If not how can we arrange that you get the new version?

Frank

**Comment by FrankBijnen** [comment]
Hello @butterflo ,

Added CTRL/X and CTRL/V. I'm happy with the result. Can you test please?

Frank
