### ISSUE TITLE
[feature request] Ideas for optimizing UI in the Filelist window section

### ISSUE THREAD

**Issue by AngusPhoe** [FrankBijnen/ExifToolGui#484]
Hi Frank,

hope not to upset you with the following. Its really low priority but could improve the intuitivity of user interface.

In the Filelist Section there are - status quo - 6 control elements:

1. Refresh button
2. a file filter selection (drop down) field
3. an EDIT button for the file filter
4. a "Details:" button, that however has another functionality, i.e. switching between thumbnail and file list view
5. a selection (drop down) field for chosing different column settings in the file list view
6. an EDIT button for this selection field (when "user defined" is selected)

These 6 elements make up two rows and leaving much empty space in the top right. See screenshot #1 

![1orig](https://github.com/user-attachments/assets/77f947d5-37dd-40a9-82f2-9a6635dc8f1c)

I could imagine to improve the UI and intuitivity by 
a) arranging the control elements in one row
b) grouping the control elements
c) adding und changing the naming of some control elements,
see next screenshot (simple UI mockup, bold appearing text is supposed to be the same style as the other text). 

![2edit](https://github.com/user-attachments/assets/eeeda26b-4a67-42ee-bc02-70746a377ae4)

When clicking buttons "Subdir" and "Thumbs", their color change to yellow (selected mode)

What do you think?

Kind regards,

Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

First of all. I'm very pleased with your comments. 

Some general remarks:
- GUI should be as user-friendly and intuitive as possbile.
- What that means should be defined by users in the first place, not by me. That's why I like user comments.
- On the other hand; I would like to retain the original layout, as designed by Bogdan, as much as possible.
- Low priority. I agree. Let's first make the subfolders work in V6.3.5.
- But we can brainstorm.

Now in more detail:

- The minimum space for the middle panel needed is defined to ensure that the buttons 'ExifTool direct' and 'Show Log window' are always visible.  The actual space left at the top is not as big as you think,
- To make more room, I could increase the minimum width for the middle panel. But that would mean less space for the Metadata/OSM map panel.
- I do agree that the text 'Details' is confusing. It was for me at first.

My thoughts:

- In stead of Buttons with texts (Refresh, Details, Edit 2x) I would prefer speed buttons with just an icon. They are smaller. Especially when translated in other languages texts can grow.
- The 2 Edit buttons dont belong there. They belong to Preferences. You dont want them visible all the time.
- I really liked the idea of adding /s to the file filter. I even considered adding /sn, where n=levels. So /s4 would mean scan subdirectories up to 4 levels. With a button that is not possible. 

Frank

![Spaceleft](https://github.com/user-attachments/assets/02db3288-70b5-4155-ba15-8378db28ed7a)

**Comment by FrankBijnen** [comment]
Just an idea. We could use 'dropdown buttons'. Buttons that show a popup menu when clicked, Here is an example what I mean. 

Initial view. Using only little space. 'Refresh' replaced by a speed button.

![filelist_overview](https://github.com/user-attachments/assets/de1ffc6a-2815-4ccd-8e0c-93849a0adb24)

The filetypes dropdown:
![filelist_types](https://github.com/user-attachments/assets/1d1e3bd1-4eaa-47e2-b0a3-b001a663bbb5)

The View dropdown. Icons left to the text need to be defined. Note that it would allow switching thumbnail sizes easier. 

![filelist_view](https://github.com/user-attachments/assets/f0110250-136a-4e87-b918-4e2afb14b376)

Frank

**Comment by AngusPhoe** [comment]
> My thoughts:
>
>  In stead of Buttons with texts (Refresh, Details, Edit 2x) I would prefer speed buttons with just an icon. They are smaller. 
Especially when translated in other languages texts can grow.

I would also prefer icons

>  The 2 Edit buttons dont belong there. They belong to Preferences. You dont want them visible all the time.

Absolutely agree

>   I really liked the idea of adding /s to the file filter. I even considered adding /sn, where n=levels. So /s4 would mean scan subdirectories up to 4 levels. With a button that is not possible.

I am neutral in this issue. 

But what I just discovered is, that the selected file filter and the selected metadata filter are not persistant after quiting and starting the program. I always change these two selections after starting the program. What do you think about making these two selections persistant?

**Comment by AngusPhoe** [comment]
> Just an idea. We could use 'dropdown buttons'. Buttons that show a popup menu when clicked, Here is an example what I mean.
> 
> Initial view. Using only little space. 'Refresh' replaced by a speed button.
> 
> ![filelist_overview](https://private-user-images.githubusercontent.com/63312605/355019163-de1ffc6a-2815-4ccd-8e0c-93849a0adb24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODgyNzIsIm5iZiI6MTcyMjg4Nzk3MiwicGF0aCI6Ii82MzMxMjYwNS8zNTUwMTkxNjMtZGUxZmZjNmEtMjgxNS00Y2NkLThlMGMtOTM4NDlhMGFkYjI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMmIwYjljMTJhMDc5N2I3ZDU1NjUxNTcxMGNiMDI1MDVhZWZiNWZjZjkyNjg0NjliNGI1ZjdiY2U1ODkxOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6s8iD3z8XxIlmC2w1uv8SR1gF5L1aP_dxWVD5q29l8)
> 
> The filetypes dropdown: ![filelist_types](https://private-user-images.githubusercontent.com/63312605/355019197-1d1e3bd1-4eaa-47e2-b0a3-b001a663bbb5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODgyNzIsIm5iZiI6MTcyMjg4Nzk3MiwicGF0aCI6Ii82MzMxMjYwNS8zNTUwMTkxOTctMWQxZTNiZDEtNGVhYS00N2UyLWIwYTMtYjAwMWE2NjNiYmI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzU0NmZkNWEzMTljOGQ5YmY3N2U2YmViM2JjNmQ4MTZkYTYxMDZhMmU5NDQyZDJjNjZiOGRmNTIyODdhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-5VyYqUQR82hM5Db4kFP1RnUVnVX_r-cE3B7YhkDxI)
> 
> The View dropdown. Icons left to the text need to be defined. Note that it would allow switching thumbnail sizes easier.
> 
> ![filelist_view](https://private-user-images.githubusercontent.com/63312605/355019235-f0110250-136a-4e87-b918-4e2afb14b376.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODgyNzIsIm5iZiI6MTcyMjg4Nzk3MiwicGF0aCI6Ii82MzMxMjYwNS8zNTUwMTkyMzUtZjAxMTAyNTAtMTM2YS00ZTg3LWI5MTgtNGUyYWZiMTRiMzc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE5NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYTg3ODg3MWYwN2YzZjFmNGU2Y2RmZmZiNzZjYjg0YTE1ZmY3MTc4ZDNlN2NiYjE1MjgzMjg3MzRkODAzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wEH--u8jyn1A5g-YzCG9iLjVxELPdUO9w_Jj1x19yo)
> 
> Frank

Hi Frank, 

very interesting idea. Would there be something like a check mark beside the selected "options"? And referring to my previous comment: in the popup down menu there could be a selectable option "remember latest selection" or so.

Thanks for be so responsive!

Angus

**Comment by FrankBijnen** [comment]
Good to read we agree largely.

> But what I just discovered is, that the selected file filter and the selected metadata filter are not persistant after quiting and starting the program. I always change these two selections after starting the program. What do you think about making these two selections persistant?

It's true that the program reverts to 'Show all files' always, but the 'metadata filter' is saved and restored. If you check 'save File Details state on exit' in Preferences.
I see no problem in also adding the file filter.

**Comment by FrankBijnen** [comment]
> Would there be something like a check mark beside the selected "options"? 

- I could do that.
- Other option would be to change the text of the button according to what is chosen.
- And if course some icons to display on the left.

Let's keep this issue open for a future version. First get the sub directories working.

Frank

**Comment by AngusPhoe** [comment]
> Good to read we agree largely.
> 
> > But what I just discovered is, that the selected file filter and the selected metadata filter are not persistant after quiting and starting the program. I always change these two selections after starting the program. What do you think about making these two selections persistant?
> 
> It's true that the program reverts to 'Show all files' always, but the 'metadata filter' is saved and restored. If you check 'save File Details state on exit' in Preferences. I see no problem in also adding the file filter.

great!

**Comment by AngusPhoe** [comment]
> > Would there be something like a check mark beside the selected "options"?
> 
>     * I could do that.
> 
>     * Other option would be to change the text of the button according to what is chosen.
> 
>     * And if course some icons to display on the left.
> 
> 
> Let's keep this issue open for a future version. First get the sub directories working.
> 
> Frank

Yes. One step after the other. ;-)

**Comment by FrankBijnen** [comment]
@AngusPhoe 
Hi Angus,

I have been working on this issue, and I think it is coming along quite nicely. In fact I expect to have something ready next week. (before Oct 19) Would you have the time and be willing to test it, and provide me with your feedback?

You know I value your opinion, and I would appreciate it very much if you did. Thanks in advance.

Frank

**Comment by AngusPhoe** [comment]
@FrankBijnen : Hi Frank, I would be delighted if I can test the new features.

Kind regards, Angus

**Comment by FrankBijnen** [comment]
@AngusPhoe 

Hi Angus, Thanks in advance for helping me test GUI!

The program is largely ready, but I do need to write some documentation before I let you play with it. Expect something within the next days.

As a teaser, here are some screenshots.

1) The new menu, only has 4 buttons.

- Refresh
- 'Details to Display' (The actual text changes when you select one)
- 'Files to filter' (Also changes)
- Export

![filelist](https://github.com/user-attachments/assets/0014cc4f-0d91-4ec1-9840-404549556a98)

2) The Thumbnails/Details popup menu 
![filelist_details](https://github.com/user-attachments/assets/39c21fcf-af2f-4084-94c2-217f2774d03e)

3) The Filter popup menu.
![filelist_filter](https://github.com/user-attachments/assets/95dc442b-5bda-44ed-bc29-83b749ad0431)

4) Export popup menu.
![filelist_export](https://github.com/user-attachments/assets/d49955b6-e8af-4497-8143-d01338e52c47)

The new configuration of the details:
(Where you can choose which columns to display)
![details_configure](https://github.com/user-attachments/assets/74bc6b8f-d1bc-44cb-8997-84142abda51e)

The modified filter menu:
![filter_configure](https://github.com/user-attachments/assets/1b4c14d5-894b-461d-9751-ca065ac78845)

Frank

**Comment by FrankBijnen** [comment]
Hi Angus,

Here it is. I hope you will be just as pleased as I am with the new GUI design. Very good of you to propose changes! 
Please let me know what you think. Dont be afraid to be critrical! Your input is very valuable to me.

Here is the downloadlink:
https://1drv.ms/f/s!AhVJC-QzM33pknOS7KwBi09lgNql?e=n7ztFX

The zip file contain the usual Exe/Map files and a PDF to get you started.

Thanks in advance for taking the time to test,
Frank

P.S. This update also contains other changes, you should be able to find the issues here. But I dont expect they will cause trouble.

**Comment by AngusPhoe** [comment]
Hello Frank,

I only have few minutes and will write more tomorrow. So far I can only say: I love it. Intuitively, and everything works!

Thanks a lot for your effort!

Kind regards,
Angus

**Comment by AngusPhoe** [comment]
(I still need to experience the new Configure Filelist columns feature). Will do it tomorrow.

**Comment by FrankBijnen** [comment]
Thanks. Take your time.

I'm still fixing bugs and update the pre-rel. So please before you start testing, check for a new version. In case I forget to notify you.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

I test everything that came into my mind. I did not find any serious bug (2 hints further down the comment).

First, I tested the prerelease without reading the pdf. I got along very well, which stands for very good programming on your side. As mentionied yesterday, everything is very intiuitive (for me).
After reading the documentation I understood the performance topic. 

One thing I discovered during reading the documention is - IMO - the inconsinstent wording:

- in the docu: "Configure Filelist columns" --> logic
- in the application, filelist section, in the thumbnail/details menu --> "Configure" --> consistent
- in the now opended settings dialog --> "Edit file columns" --> I would suggest "Configure/Edit file_list_ columns" or even more general "Configure filelists"
- in the Program menu --> "User defined fields definition file" --> user defined fields is not specific enough, because this could mean many things (filelist, workspace, custom). My suggestion would be "Filelists definition file" which might be correct but difficult in sounding and understanding. Maybe you have a better suggestion.

A second thing I discovered is the following behaviour: After having defined and saved a filelist with the according filelist columns, I entered again the "Edit file columns" dialog. When selecting the three points in a command field, the now opened "Select tag name" dialog always shows the prefilled values "1 Specific location / All / :All" instead of the previously defined ones. It is not a bug, but IMO a strange behaviour. Nothing serious though.

Kind regards,
Daniel

**Comment by FrankBijnen** [comment]
@AngusPhoe 

Hi Angus,

I have just uploaded a new pre-rel. Fixes included:

- Fixed another memory-leak that showed when using 'Select all' with a lot of files (5000+) I will spare you the details, but it took a lot of debugging.
- Changed the menu-items names, to be more consistent. As you proposed, but with one exception 'Filelist' -> 'File list'. The English like adding spaces. Turns out that it was already wrong in V516. (Bogdan was not native English either)
- Changed the initial display in the 'Select tag name' dialog. I think it works better, but please decide for yourself.
Note: Did you notice that when you edit an 'Internal' file list, the lookup is different?
- I started translating into different languages. (You probably dont care, I know you prefer English programs)
- Various small fixes, I cant remember now

My thoughts about version V6.3.6.
- I think it's getting close. Thanks to you!
- I dont want to add new functionality. Just testing, bug fixing and docs updating.
- When you have the time, please try it. My feeling is that you could use it as 'production'.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

just wanted to inform you that I was very busy the last days and couldn't test anything. I hope to be able to test the new version on Thursday evening.

Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

To be clear. I appreciate your efforts very much, and I understand when other things are more important. So no excuses please...

Maybe it's only for better, because I have just updated the Pre-rel again. I fixed some issue with refreshing the filelist, and did some work on #616.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

I did some testing today. 

> Changed the menu-items names, to be more consistent. As you proposed, but with one exception 'Filelist' -> 'File list'. The English like adding spaces. Turns out that it was already wrong in V516. (Bogdan was not native English either)

✅ 

> Changed the initial display in the 'Select tag name' dialog. I think it works better, but please decide for yourself.

✅ I like it. (not sure about the rest of the world ;-) )

> Note: Did you notice that when you edit an 'Internal' file list, the lookup is different?

yes I noticed that. And I liked, that the intial display included the previously saved values. That's why I thought it might be good to have the same behaviour for the "exiftool read mode". 

I discovered another "strange?" behaviour. I will post it in the next comment for separate tracking.

**Comment by FrankBijnen** [comment]
Once again. Thank you very much.

Looking forward to know more about the "strange behaviour", but please take your time. No hurry....

**Comment by AngusPhoe** [comment]
Hi Frank, 

I discovered a new behaviour, that did not exist in version 6.3.5. I wonder if you implemented it intentionally.

1. navigating to a folder in the left-hand "Folders" frame. 
--> ✅ 1. result: In the "file list" frame the according files are listed. 
--> ✅ 2. result: the "Folders" frame has now a horizontal bar, because sub folders a lengthy
2. selecting one file in the "file list" frame
--> ✅ 1. result: Metadata are shown in the according frame 
--> ❓ 2. result: the folders tree in the "Folders" frame is moved to the right.  The selected folder remains selected but is now only partially visible. I could not observe this behaviour in version 6.3.5

If I could not explain well enough, please tell me. I would then try to record a screen cast (with nomeaning folder and file names)

**Comment by FrankBijnen** [comment]
Hi Angus,

See https://github.com/FrankBijnen/ExifToolGui/issues/558

Frank

**Comment by AngusPhoe** [comment]
I think I found another issue (IMO mid prio): 

The last selected file filter is not remembered after restart of the program.
"save Filelist Details state on exit" is/was selected.

P.S. As you mentioned, the word "Filelist" is actually "file list". In the settings dialog, the word "filelist" still exists in the tabs "General" (1x) and "Other" (4x)

P.P.S. Hope my spelling comments are not too penible. 😟  I believe this tick is is a result from correcting the homework of my kids.

**Comment by FrankBijnen** [comment]
Angus,

>The last selected file filter is not remembered after restart of the program.
"save Filelist Details state on exit" is/was selected.

It's true, but that is on purpose. In fact the code to restore the setting is commented. I tried it, but decided not to enable that for 2 reasons:

1. If you look at the doc (that was created by Bogdan) it says "-is set to Show ALL files by default on every GUI startup and this behaviour can't be changed. " https://github.com/FrankBijnen/ExifToolGui/blob/main/Docs/ExifToolGUI_V6.md#filelist-panel
2. Suppose you exited the program with subfolders enabled and a large number of subfolders, then the next startup would take very long.

I'm open to suggestions, if I can prevent case 2 from happening.

I will look into the 'filelist' 'file list' issues. And no I dont mind, in fact I like it.

Frank

**Comment by FrankBijnen** [comment]
> (Does this topic require an own issue?)

That's up to you. If you agree to leave it as it is (and always was) then no new issue is needed.

>When opening the program and a huge list of files has to be parsed (independent if subfolders are selected or not), 

There is already something like that in GUI. I mean this dialog, where you can click Close. 
The problem is when to show the dialog. What exactly is the treshhold? I only know how many files there are once I finished scanning. 
Of course I could always show it, but that would be overkill.

![scan folders](https://github.com/user-attachments/assets/c64d57ee-a9a6-4e96-8c2e-10f4b1614124)

Think about it and reply when it's convenient for you.

Frank

**Comment by AngusPhoe** [comment]
Hi Frank,

> > (Does this topic require an own issue?)
> 
> That's up to you. If you agree to leave it as it is (and always was) then no new issue is needed.

I have to admit, that an option "remember last file filter" would be a nice feature. However, as I wrote above: not crucial.


> > When opening the program and a huge list of files has to be parsed (independent if subfolders are selected or not),
> 
> There is already something like that in GUI. I mean this dialog, where you can click Close.

True, I never realized this dialog, because parsing the files is so super fast (on my computer) and I normally don't edit a huge number of files in one view. 

For the first time, I tested the following scenario: I copied 10k image files into my default exiftool editing folder (without subfolders). The startup is quit long. So in fact, even today point 2 (... then the next startup would take very long) exists - indepent of having a remembered "/s" file filter. 

My naive proposal would be - for both cases: many files in the startup folder, many files in subfolders of the startup folder - the following:

1. startup of the program
   --> the GUI is shown
2. the parsing of the files in the startup folder (and maybe subfolders) starts - identically as if a user has manually selected a folder
   --> the already exisiting scanning dialog is shown (in case of a low number of files a user would not even recognize the dialog)
3. in case that the user percieves the scanning too long, he/she can abort (ESC).

I know, many things would have to be changed...

Kind regards,
Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

Good to read something from you again..

Meanwhile I have changed something to the configuration of the file filters. I know it doesn't solve the issue's, regard it as an interim solution. (Pre-rel is updated)

![config_filefilter](https://github.com/user-attachments/assets/85456d50-e056-42e1-be96-01ededc5f589)

The user can choose wich filter to use at startup, by checking the line. I have also added some more file type, that can be added by the defaults button.

Let me try to explain what is difficult for me.

The startup time is not only dependent on the nr. of files. Some causes beyond my control:
- General performance of the hardware. in particular Hard drive, or Network share.
- Windows uses caching. the second time is usually faster.
- The details selected. It makes quite a difference if you have Thumbnails (that may need to be generated first), User defined details (invoking ExifTool.exe), or a simple standard filelist. (BTW: What kind of details did you use for your test?)
- So just counting the nr. of files is not enough.

 What's more. To get the nr. of files you first have to enumerate the directories. Then decide if you want to show a dialog, and then enumerate the directories again!
And then the big question: What is the treshold (how many files) to show a dialog?

A better solution would be:
- Start processsing 
- If it does not complete within xxx nr of seconds (how many?) show the dialog.
- But that would require a lot of changes to elemental code.

The reason I chose to use '/s' is because that is something that I introduced. It wasn't there in previous versions. So if you did your test in V516, the effect would be the same. But if you start and you dont know '/s' is remembered from last time, it may come as a surprise, if that directory has a lot of sub folders.
Also I believe that GeoSetter's Flat mode is not activated by default. That must be for a reason!

So yes, I agree that it would be nice to have, but for me difficult to implement. My proposal is to start with the checkbox for this version, and to create an issue for a future version.

I am thinking of redesigning the file filter. I would like to add a Description and show that in the toolbar. and add more filtering options. (File type, Size, Date created, and maybe metadata) Maybe by the time I start working on that I have ideas how to implement the possible lengthy startup issue.

Frank

P.S. Thanks for your time....

**Comment by AngusPhoe** [comment]
Hi Frank,

> Meanwhile I have changed something to the configuration of the file filters. I know it doesn't solve the issue's, regard it as an interim solution.

In my opinion, it does solve the issue. It works! 

> BTW: What kind of details did you use for your test?

I scanned my files located on my internal SSD hard drive (super fast). And I used the following file list (exiftool-based) for testing
![{9646726F-E165-404B-BA0C-DD5A96DD908B}](https://github.com/user-attachments/assets/3110a9cc-3891-4eca-b34b-1c108e148224)

> Also I believe that GeoSetter's Flat mode is not activated by default. That must be for a reason!

True.

> My proposal is to start with the checkbox for this version, and to create an issue for a future version.

I fully agree. The changes you have done so far are already awesome (Strg+S, /s, ESC, ...) Thanks for that.

Kind regards,

Angus

**Comment by FrankBijnen** [comment]
Hi Angus,

Glad you agree.

>I scanned my files located on my internal SSD hard drive (super fast). And I used the following file list (exiftool-based) for testing

About your test, that is about the slowest possible, Looks like movies (VideoCodec) so large files, and ExifTool has to get the data. But that doesn't mean I will not address it.

Will you create the issue, or shall I do that?

I have made a start with updating the docs. not so much fun. But necessary. Will keep you posted.

Frank

**Comment by AngusPhoe** [comment]
> Will you create the issue, or shall I do that?

yes, I will
